// Code generated by protoc-gen-go. DO NOT EDIT.
// source: root.proto

package root

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Source struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a043f6ee9336a8, []int{0}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a043f6ee9336a8, []int{1}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FileLoaded struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileLoaded) Reset()         { *m = FileLoaded{} }
func (m *FileLoaded) String() string { return proto.CompactTextString(m) }
func (*FileLoaded) ProtoMessage()    {}
func (*FileLoaded) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a043f6ee9336a8, []int{2}
}

func (m *FileLoaded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileLoaded.Unmarshal(m, b)
}
func (m *FileLoaded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileLoaded.Marshal(b, m, deterministic)
}
func (m *FileLoaded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileLoaded.Merge(m, src)
}
func (m *FileLoaded) XXX_Size() int {
	return xxx_messageInfo_FileLoaded.Size(m)
}
func (m *FileLoaded) XXX_DiscardUnknown() {
	xxx_messageInfo_FileLoaded.DiscardUnknown(m)
}

var xxx_messageInfo_FileLoaded proto.InternalMessageInfo

func (m *FileLoaded) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Output struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a043f6ee9336a8, []int{3}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Interrupt struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interrupt) Reset()         { *m = Interrupt{} }
func (m *Interrupt) String() string { return proto.CompactTextString(m) }
func (*Interrupt) ProtoMessage()    {}
func (*Interrupt) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a043f6ee9336a8, []int{4}
}

func (m *Interrupt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interrupt.Unmarshal(m, b)
}
func (m *Interrupt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interrupt.Marshal(b, m, deterministic)
}
func (m *Interrupt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interrupt.Merge(m, src)
}
func (m *Interrupt) XXX_Size() int {
	return xxx_messageInfo_Interrupt.Size(m)
}
func (m *Interrupt) XXX_DiscardUnknown() {
	xxx_messageInfo_Interrupt.DiscardUnknown(m)
}

var xxx_messageInfo_Interrupt proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Source)(nil), "root.Source")
	proto.RegisterType((*File)(nil), "root.File")
	proto.RegisterType((*FileLoaded)(nil), "root.FileLoaded")
	proto.RegisterType((*Output)(nil), "root.Output")
	proto.RegisterType((*Interrupt)(nil), "root.Interrupt")
}

func init() {
	proto.RegisterFile("root.proto", fileDescriptor_08a043f6ee9336a8)
}

var fileDescriptor_08a043f6ee9336a8 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4b, 0x05, 0x21,
	0x10, 0xc6, 0xb1, 0x67, 0x1b, 0xce, 0x7b, 0x50, 0xcc, 0x69, 0x79, 0x74, 0x10, 0x4f, 0xd2, 0x61,
	0x7b, 0xbc, 0xfe, 0x83, 0x82, 0x20, 0x08, 0x02, 0xbb, 0x75, 0x09, 0x37, 0x0d, 0x16, 0x76, 0x55,
	0x4c, 0xff, 0xff, 0x50, 0x97, 0xed, 0xd2, 0xed, 0x73, 0xbe, 0xf9, 0xcd, 0x7c, 0x0e, 0x40, 0xf4,
	0x3e, 0x0d, 0x21, 0xfa, 0xe4, 0x91, 0x16, 0x2d, 0xee, 0xa0, 0x7b, 0xf7, 0x39, 0x7e, 0x59, 0xe4,
	0x70, 0xf9, 0x3d, 0xcd, 0xf6, 0xa7, 0x27, 0x7c, 0x27, 0xf7, 0x67, 0x18, 0x6a, 0xef, 0xf3, 0x34,
	0x5b, 0xd5, 0x0c, 0x31, 0x00, 0x2d, 0x4f, 0x44, 0xa0, 0x4e, 0x2f, 0xb6, 0x27, 0x9c, 0x48, 0xa6,
	0xaa, 0x2e, 0x35, 0xa3, 0x93, 0xee, 0x2f, 0x38, 0x91, 0x07, 0x55, 0xb5, 0xe0, 0x00, 0xa5, 0xff,
	0xd5, 0x6b, 0x63, 0xcd, 0x7f, 0x94, 0xb8, 0x85, 0xee, 0x2d, 0xa7, 0x90, 0xd3, 0xc6, 0xaf, 0x6e,
	0xe5, 0xf7, 0xc0, 0x5e, 0x5c, 0xb2, 0x31, 0xe6, 0x90, 0xce, 0x9f, 0xc0, 0x9e, 0xfc, 0xb2, 0x68,
	0x67, 0x6c, 0x44, 0x09, 0xb4, 0x4c, 0xc5, 0x43, 0x0b, 0xd9, 0x7e, 0x70, 0xbc, 0xf9, 0x8b, 0xdc,
	0x76, 0x9e, 0x08, 0x4a, 0xd8, 0xa9, 0xec, 0xf0, 0xba, 0x59, 0xdb, 0xb8, 0xe3, 0x4a, 0xb6, 0xed,
	0x92, 0x9c, 0xc8, 0x23, 0xfb, 0xb8, 0x0a, 0xe3, 0x7d, 0xa9, 0x8e, 0x5d, 0xbd, 0xd0, 0xc3, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x31, 0x7f, 0xcc, 0x2f, 0x01, 0x00, 0x00,
}
